//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enabill.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enabill.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expense can only be created for yourself.
        /// </summary>
        public static string ERR_CreateExpense_Message {
            get {
                return ResourceManager.GetString("ERR_CreateExpense_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an hourly contracted user and therefore, FlexiBalances do not apply to &quot; + {1} + &quot;. This page cannot be viewed.&quot;.
        /// </summary>
        public static string ERR_HourlyContractedUser_Message {
            get {
                return ResourceManager.GetString("ERR_HourlyContractedUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexiTime does not apply to {0}.
        /// </summary>
        public static string ERR_HourlyContractedUser_Title {
            get {
                return ResourceManager.GetString("ERR_HourlyContractedUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity being deleted could not be found. Delete cancelled..
        /// </summary>
        public static string ERR_NoActivityForDelete_Message {
            get {
                return ResourceManager.GetString("ERR_NoActivityForDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity being updated could not be found. Update of activity cancelled..
        /// </summary>
        public static string ERR_NoActivityForUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoActivityForUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected client could not be found..
        /// </summary>
        public static string ERR_NoClient_Message {
            get {
                return ResourceManager.GetString("ERR_NoClient_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client could not be found and therefore, the contact cannot be retrieved..
        /// </summary>
        public static string ERR_NoClientForContact_Message {
            get {
                return ResourceManager.GetString("ERR_NoClientForContact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client to which this contact would be assigned could not be found. Creation of the contact was cancelled..
        /// </summary>
        public static string ERR_NoClientForContactCreate_Message {
            get {
                return ResourceManager.GetString("ERR_NoClientForContactCreate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client of the contact being deleted could not be found. Delete of contact cancelled..
        /// </summary>
        public static string ERR_NoClientForContactDelete_Message {
            get {
                return ResourceManager.GetString("ERR_NoClientForContactDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client that owns this contact could not be found. Update of contact was cancelled..
        /// </summary>
        public static string ERR_NoClientForContactUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoClientForContactUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected client could not be found. The look up for contacts of the client was cancelled..
        /// </summary>
        public static string ERR_NoClientForRetrieveContactList_Message {
            get {
                return ResourceManager.GetString("ERR_NoClientForRetrieveContactList_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected contact could not be found..
        /// </summary>
        public static string ERR_NoContact_Message {
            get {
                return ResourceManager.GetString("ERR_NoContact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact being updated could not be found. Update to contact cancelled..
        /// </summary>
        public static string ERR_NoContactForUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoContactForUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected expense could not be found.
        /// </summary>
        public static string ERR_NoExpense_Message {
            get {
                return ResourceManager.GetString("ERR_NoExpense_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have the &apos;Time Capturer&apos; role and therefore, this page cannot be viewed for {1}..
        /// </summary>
        public static string ERR_NonTimeCapturerUser_Message {
            get {
                return ResourceManager.GetString("ERR_NonTimeCapturerUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a &apos;Time Capturer&apos;.
        /// </summary>
        public static string ERR_NonTimeCapturerUser_Title {
            get {
                return ResourceManager.GetString("ERR_NonTimeCapturerUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required permissions to edit a region. Save cancelled..
        /// </summary>
        public static string ERR_NoPermissionToUpdateRegion {
            get {
                return ResourceManager.GetString("ERR_NoPermissionToUpdateRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required permissions to view this page..
        /// </summary>
        public static string ERR_NoPermissionToViewPage_Message {
            get {
                return ResourceManager.GetString("ERR_NoPermissionToViewPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project could not be found..
        /// </summary>
        public static string ERR_NoProject_Message {
            get {
                return ResourceManager.GetString("ERR_NoProject_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project that the selected activity belongs to could not be found..
        /// </summary>
        public static string ERR_NoProjectForActivity_Message {
            get {
                return ResourceManager.GetString("ERR_NoProjectForActivity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project that would own the activity being created could not be found. Creation of activity cancelled..
        /// </summary>
        public static string ERR_NoProjectForActivityCreate_Message {
            get {
                return ResourceManager.GetString("ERR_NoProjectForActivityCreate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project that owns the activity being deleted could not be found. Delete of activity cancelled..
        /// </summary>
        public static string ERR_NoProjectForActivityDelete_Message {
            get {
                return ResourceManager.GetString("ERR_NoProjectForActivityDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project could not be found, therefore, no activities for the project could be displayed..
        /// </summary>
        public static string ERR_NoProjectForActivityList_Message {
            get {
                return ResourceManager.GetString("ERR_NoProjectForActivityList_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project that owns the activity being updated could not be found. Update of activity cancelled..
        /// </summary>
        public static string ERR_NoProjectForActivityUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoProjectForActivityUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project could not be found. Update to project cancelled..
        /// </summary>
        public static string ERR_NoProjectForUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoProjectForUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected region could not be found..
        /// </summary>
        public static string ERR_NoRegion_Message {
            get {
                return ResourceManager.GetString("ERR_NoRegion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected region could not be found. Update to region cancelled..
        /// </summary>
        public static string ERR_NoRegionForUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoRegionForUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a region name..
        /// </summary>
        public static string ERR_NoRegionName_Message {
            get {
                return ResourceManager.GetString("ERR_NoRegionName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a region short code..
        /// </summary>
        public static string ERR_NoRegionShortCode_Message {
            get {
                return ResourceManager.GetString("ERR_NoRegionShortCode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a region status..
        /// </summary>
        public static string ERR_NoRegionStatus_Message {
            get {
                return ResourceManager.GetString("ERR_NoRegionStatus_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected user could not be found..
        /// </summary>
        public static string ERR_NoUser_Message {
            get {
                return ResourceManager.GetString("ERR_NoUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work allocation to which this note belongs could not be found. Save cancelled..
        /// </summary>
        public static string ERR_NoWorkAllocationForNoteCreateUpdate_Message {
            get {
                return ResourceManager.GetString("ERR_NoWorkAllocationForNoteCreateUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested work allocation could not be found..
        /// </summary>
        public static string ERR_NoWorkAllocationFound_Message {
            get {
                return ResourceManager.GetString("ERR_NoWorkAllocationFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context work session could not be found..
        /// </summary>
        public static string ERR_NoWorkSession_Message {
            get {
                return ResourceManager.GetString("ERR_NoWorkSession_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date is either a public holiday or a weekend..
        /// </summary>
        public static string ERR_WeekendPublicHoliday_Message {
            get {
                return ResourceManager.GetString("ERR_WeekendPublicHoliday_Message", resourceCulture);
            }
        }
    }
}
